In [261]:
import numpy as np
import random

In [274]:
class Game():
    def __init__(self):
        self.board = np.zeros(16).reshape(4, 4)

    def new_piece(self):
        print("NEW PIECE")
        flattened_board = self.board.reshape(16)
        empty_spots = np.where(flattened_board == 0)[0]
        print("\tEMPTY SPOTS: ", empty_spots)
        new_spot = random.randint(0, len(empty_spots) - 1)
        print("\tNEW SPOT: ", new_spot)
        flattened_board[new_spot] = 2
        self.board = flattened_board.reshape(4, 4)

    def left(self):
        for i in range(0, 4):
            for m in range(0, 4):
                merged = False
                
                for n in range(1, 4):
                    if not merged and self.board[m][n - 1] == self.board[m][n]:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n - 1] * 2, 0
                        merged = True
                        
                    if self.board[m][n - 1] == 0 and self.board[m][n] != 0:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n], 0
                
    def right(self):
        for i in range(0, 4):
            for m in range(0, 4):
                merged = False
                
                for n in range(2, -1, -1):
                    if not merged and self.board[m][n] == self.board[m][n + 1]:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m][n + 1] == 0:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n]



In [275]:
game = Game()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [276]:
game.new_piece()
game.new_piece()

NEW PIECE
	EMPTY SPOTS:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
	NEW SPOT:  7
NEW PIECE
	EMPTY SPOTS:  [ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15]
	NEW SPOT:  5


In [277]:
game.board

array([[0., 0., 0., 0.],
       [0., 2., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [278]:
game.left()

In [279]:
game.board

array([[0., 0., 0., 0.],
       [4., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [280]:
game.right()

In [281]:
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])