In [1]:
import numpy as np
import random

# Game Engine

In [2]:
class Game():
    def __init__(self):
        self.board = np.zeros([4, 4])

    def new_piece(self):
        flattened_board = self.board.reshape(16)
        empty_spots = np.where(flattened_board == 0)[0]
        new_spot = random.randint(0, len(empty_spots) - 1)
        flattened_board[new_spot] = 2
        self.board = flattened_board.reshape(4, 4)

    def left(self):    
        for m in range(0, 4):
            merged = False # only allow one merge per row per turn, as per the rules
            
            for i in range(0, 4):
                for n in range(1, 4):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n - 1] == self.board[m][n]:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n - 1] * 2, 0
                        merged = True
                        
                    if self.board[m][n - 1] == 0 and self.board[m][n] != 0:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n], 0
                
    def right(self):
        for m in range(0, 4):
            merged = False # only allow one merge per row per turn, as per the rules

            for i in range(0, 4):
                for n in range(2, -1, -1):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n] == self.board[m][n + 1]:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m][n + 1] == 0:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n]

    def up(self):
        for n in range(0, 4):
            merged = False # only allow one merge per column per turn, as per the rules
            
            for i in range(0, 4):
                for m in range(1, 4):
                    if not self.board[m][n] == 0 and not merged and self.board[m - 1][n] == self.board[m][n]:
                        self.board[m - 1][n], self.board[m][n] = self.board[m - 1][n] * 2, 0
                        merged = True
                        
                    if self.board[m - 1][n] == 0 and self.board[m][n] != 0:
                        self.board[m - 1][n], self.board[m][n] = self.board[m][n], 0

    def down(self):
        for n in range(0, 4):
            merged = False # only allow one merge per column per turn, as per the rules

            for i in range(0, 4):
                for m in range(2, -1, -1):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n] == self.board[m + 1][n]:
                        self.board[m][n], self.board[m + 1][n] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m + 1][n] == 0:
                        self.board[m][n], self.board[m + 1][n] = 0, self.board[m][n]


# Test new piece generation and basic movement

In [3]:
game = Game()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
game.new_piece()
game.new_piece()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [5]:
game.left()
game.board

array([[0., 0., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [6]:
game.right()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 2.]])

# Test merge left

In [7]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
game.left()
game.board

array([[4., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Test merge right

In [9]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
game.right()
game.board

array([[0., 0., 0., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Test merge up

In [11]:
game = Game()
game.board[0][0], game.board[3][0] = 2, 2
game.board

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [12]:
game.up()
game.board

array([[4., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Test merge down

In [13]:
game = Game()
game.board[0][0], game.board[3][0] = 2, 2
game.board

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [14]:
game.down()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 0., 0., 0.]])