In [37]:
import numpy as np
import random
import math

# Game Engine

In [38]:
random.randint(0, 10)

3

In [39]:
class Game():
    def __init__(self):
        self.board = np.zeros([4, 4])
        self.last = None

    def new_piece(self):
        flattened_board = self.board.reshape(16)
        empty_spots = np.where(flattened_board == 0)[0]
        
        if len(empty_spots) == 0:
            return False
        else:
            new_spot = empty_spots[random.randint(0, len(empty_spots) - 1)]
            print(f"New cell created at {math.trunc(new_spot / 4)},{new_spot % 4}")
            flattened_board[new_spot] = 2 if random.randint(0, 10) else 4
            self.board = flattened_board.reshape(4, 4)

        return True

    def has_lost(self):
        # TODO
        return False

    def has_won(self):
        flattened_board = self.board.reshape(16)        
        return len(np.where(flattened_board == 2048)[0]) > 0

    def can_move(self, direction):
        # TODO
        return True

    def transition_left(self):    
        for m in range(0, 4):
            merged = False # only allow one merge per row per turn, as per the rules
            
            for i in range(0, 4):
                for n in range(1, 4):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n - 1] == self.board[m][n]:
                        print(f"Cells merged into {m},{n - 1}")
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n - 1] * 2, 0
                        merged = True
                        
                    if self.board[m][n - 1] == 0 and self.board[m][n] != 0:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n], 0

    def transition_right(self):
        for m in range(0, 4):
            merged = False # only allow one merge per row per turn, as per the rules

            for i in range(0, 4):
                for n in range(2, -1, -1):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n] == self.board[m][n + 1]:
                        print(f"Cells merged into {m},{n + 1}")
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m][n + 1] == 0:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n]
            
    def transition_up(self):
        for n in range(0, 4):
            merged = False # only allow one merge per column per turn, as per the rules
            
            for i in range(0, 4):
                for m in range(1, 4):
                    if not self.board[m][n] == 0 and not merged and self.board[m - 1][n] == self.board[m][n]:
                        print(f"Cells merged into {m - 1},{n}")
                        self.board[m - 1][n], self.board[m][n] = self.board[m - 1][n] * 2, 0
                        merged = True
                        
                    if self.board[m - 1][n] == 0 and self.board[m][n] != 0:
                        self.board[m - 1][n], self.board[m][n] = self.board[m][n], 0

    def transition_down(self):
        for n in range(0, 4):
            merged = False # only allow one merge per column per turn, as per the rules

            for i in range(0, 4):
                for m in range(2, -1, -1):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n] == self.board[m + 1][n]:
                        print(f"Cells merged into {m + 1},{n}")
                        self.board[m][n], self.board[m + 1][n] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m + 1][n] == 0:
                        self.board[m][n], self.board[m + 1][n] = 0, self.board[m][n]
    
    def transition(self, direction):
        if self.can_move(direction):
            match direction:
                case 'L':
                    self.transition_left()
                case 'R':
                    self.transition_right()
                case 'U':
                    self.transition_up()
                case 'D':
                    self.transition_down()
            
            self.last = direction
            self.new_piece()          
                    

# Test new piece generation and basic movement

In [78]:
game = Game()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
game.new_piece()
game.new_piece()
game.board

New cell created at 2,2
New cell created at 1,0


array([[0., 2., 2., 2.],
       [4., 2., 2., 0.],
       [0., 0., 4., 0.],
       [2., 2., 0., 2.]])

In [42]:
game.transition('L')
game.board

New cell created at 2,3


array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 0., 0., 2.],
       [0., 0., 0., 0.]])

In [43]:
game.transition('R')
game.board 

New cell created at 1,3


array([[0., 0., 0., 2.],
       [0., 0., 0., 2.],
       [0., 0., 4., 2.],
       [0., 0., 0., 0.]])

# Test merge left

In [44]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
game.transition('L')
game.board

Cells merged into 0,0
New cell created at 1,1


array([[4., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Test merge right

In [46]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
game.transition('R')
game.board

Cells merged into 0,3
New cell created at 0,0


array([[2., 0., 0., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Test merge up

In [48]:
game = Game()
game.board[0][0], game.board[3][0] = 2, 2
game.board

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [49]:
game.transition('U')
game.board

Cells merged into 0,0
New cell created at 2,2


array([[4., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 0.]])

# Test merge down

In [50]:
game = Game()
game.board[0][0], game.board[3][0] = 2, 2
game.board

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 0., 0.]])

In [51]:
game.transition('D')
game.board

Cells merged into 3,0
New cell created at 1,2


array([[0., 0., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 0.],
       [4., 0., 0., 0.]])