In [318]:
import numpy as np
import random

In [494]:
class Game():
    def __init__(self):
        self.board = np.zeros(16).reshape(4, 4)

    def new_piece(self):
        print("NEW PIECE")
        flattened_board = self.board.reshape(16)
        empty_spots = np.where(flattened_board == 0)[0]
        print("\tEMPTY SPOTS: ", empty_spots)
        new_spot = random.randint(0, len(empty_spots) - 1)
        print("\tNEW SPOT: ", new_spot)
        flattened_board[new_spot] = 2
        self.board = flattened_board.reshape(4, 4)

    def left(self):    
        for m in range(0, 4):
            merged = False
            
            for i in range(0, 4):
                for n in range(1, 4):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n - 1] == self.board[m][n]:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n - 1] * 2, 0
                        merged = True
                        
                    if self.board[m][n - 1] == 0 and self.board[m][n] != 0:
                        self.board[m][n - 1], self.board[m][n] = self.board[m][n], 0
                
    def right(self):
        for m in range(0, 4):
            merged = False

            for i in range(0, 4):
                for n in range(2, -1, -1):
                    if not self.board[m][n] == 0 and not merged and self.board[m][n] == self.board[m][n + 1]:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n] * 2
                        merged = True
                    
                    if self.board[m][n] != 0 and self.board[m][n + 1] == 0:
                        self.board[m][n], self.board[m][n + 1] = 0, self.board[m][n]



In [495]:
game = Game()
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [496]:
game.new_piece()
game.new_piece()

NEW PIECE
	EMPTY SPOTS:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
	NEW SPOT:  13
NEW PIECE
	EMPTY SPOTS:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15]
	NEW SPOT:  4


In [497]:
game.board

array([[0., 0., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 2., 0., 0.]])

In [481]:
game.left()

In [482]:
game.board

array([[2., 0., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [483]:
game.right()

In [484]:
game.board

array([[0., 0., 0., 2.],
       [0., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [485]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [487]:
game.left()
game.board

array([[4., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [488]:
game = Game()
game.board[0][0], game.board[0][3] = 2, 2
game.board

array([[2., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [489]:
game.right()
game.board

array([[0., 0., 0., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])